on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  packages: read

env:
  DOTNET_VERSION: '10.0.x'
  NUGET_REGISTRY_URL: https://nuget.pkg.github.com/devpikachu/index.json
  NUGET_REGISTRY_USERNAME: devpikachu

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup .NET SDK 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Add NuGet repository
        run: dotnet nuget add source --name github --username $NUGET_REGISTRY_USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text $NUGET_REGISTRY_URL
      - name: Restore dependencies from cache
        uses: actions/cache@v5
        with:
          key: deps-${{ hashFiles('bootstrap.sh') }}
          path: |
            vendor/vs.tar.gz
            vendor/*.zip
      - name: Bootstrap
        run: bash bootstrap.sh
      - name: Build
        run: |
          bash build.sh --target Archive --general-project DurableBetterProspecting --general-version $GITHUB_REF_NAME
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: out/*.zip
